services:
  web:
    build: .
    container_name: spencal_app
    ports:
      - "1649:80"
    volumes:
      - .:/var/www/html
    restart: always
    # TAMBAHKAN BAGIAN INI:
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"